[package]
name = "Multi-use-Discord-bot-school"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
serenity = "0.12.5"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
